source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '14.0'

target 'ComputingForceApp' do
    pod 'Moya', '~> 15.0'
    pod 'NVActivityIndicatorView', '5.1.1'
    pod 'URLNavigator', '2.4.1'
    pod 'Swinject', '2.8.2'
    pod 'KeychainAccess', '4.2.2'
    pod 'Hue', '5.0.0'
    pod 'Charts', '4.1.0'
    pod 'FGRoute'
    pod 'IQKeyboardManagerSwift', '6.5.11'
    pod 'SDWebImage', '5.14.3'
    pod 'CombineCocoa'
    pod 'LKAlertController', '1.12.2'
    pod 'MJRefresh', '3.7.5'
    pod 'FLEX', :configurations => ['Debug']
end
