source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '14.0'

target 'ComputingForceApp' do
    pod 'Alamofire', '5.6.4'
    pod 'NVActivityIndicatorView', '5.1.1'
    pod 'URLNavigator', '2.4.1'
    pod 'FLEX', :configurations => ['Debug']
end