source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '14.0'

target 'ComputingForceApp' do
    pod 'Alamofire', '5.6.4'
    pod 'NVActivityIndicatorView', '5.1.1'
    pod 'URLNavigator', '2.4.1'
    pod 'Swinject', '2.8.2'
    pod 'KeychainAccess', '4.2.2'
    pod 'Hue', '5.0.0'
    pod 'Charts', '4.1.0'
    pod 'FLEX', :configurations => ['Debug']
end
